# . ~/dotfiles/bash/env
# . ~/dotfiles/bash/config
# . ~/dotfiles/bash/aliases

export PATH=${PATH}:$HOME/dotfiles/scripts
export PATH=${PATH}:$HOME/.rvm/scripts/rvm # add RVM to path
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

mkcd () {
	mkdir -p "$*"
	cd "$*"
}
