. ~/dotfiles/bash/aliases
. ~/dotfiles/bash/config

export VISUAL=mvim
export EDITOR=vim

export PATH=${PATH}:$HOME/bin
export PATH=${PATH}:$HOME/dotfiles/scripts
export PATH=${PATH}:$HOME/bin/git-tf

# Do I need this?
#PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

source /Users/ethanmuller/.rvm/scripts/rvm
